In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2' # no warning
import tensorflow as tf

Create two random 0-d tensors x and y of any distribution. The output should be the sum. We do the first two problem for you:

In [3]:
sess = tf.InteractiveSession()
x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.add(x,y)
print(x.eval())
print(y.eval())
print(out.eval())

0.08197737
0.7123331
1.1196841


Now try to look at variable x and y. What do you notice?


You can see that they do not 
give the result of your calculation. The reason is that:
TensorFlow has several ops that create random tensors with different distributions.
The random ops are stateful, and create new random values each time they are evaluated.
To fix this we can use tf.Variables or you can run x,y and out in the same time, see the example below.

In [4]:
x = tf.Variable(tf.random_uniform([]))  # Empty array as shape creates a scalar.
y = tf.Variable(tf.random_uniform([]))
init_op = tf.global_variables_initializer() # Init function
out = tf.add(x,y)
sess.run(init_op) # first init vars
print(x.eval())
print(y.eval())
print(out.eval())

0.36288583
0.14610791
0.50899374


Observe that now the calculation is correct. You can also use a normal session if you prefer, see below

In [5]:
with tf.Session() as sess:

    x = tf.random_uniform([])  # Empty array as shape creates a scalar.
    y = tf.random_uniform([])
    out = tf.add(x, y)
    x_out, y_out, out_out = sess.run([x,y,out])
    print(x_out)
    print(y_out)
    print(out_out)

0.051029563
0.95928776
1.0103173


1a: Create two random 0-d tensors x and y of any distribution.
Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
Hint: look up tf.cond()
We also show you how to do this one:

In [6]:
sess1 = tf.InteractiveSession()
x = tf.Variable(tf.random_uniform([]))  # Empty array as shape creates a scalar.
y = tf.Variable(tf.random_uniform([]))
init_op = tf.global_variables_initializer()
out = tf.cond(tf.greater(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))
sess1.run(init_op)
print(x.eval())
print(y.eval())
print(out.eval())
sess1.close()

0.29666758
0.040057182
0.33672476


1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
Return x + y if x < y, x - y if x > y, 0 otherwise.
Hint: Look up tf.case().

In [7]:
sess2 = tf.InteractiveSession()
x = tf.Variable(tf.random_uniform([],-1,1))
y = tf.Variable(tf.random_uniform([],-1,1))
init_op = tf.global_variables_initializer()
out = tf.cond(tf.greater(x,y),lambda:tf.subtract(x,y),lambda:tf.add(x,y))
sess2.run(init_op)
print(x.eval())
print(y.eval())
print(out.eval())
sess2.close()

0.77880764
0.3157606
0.46304703


1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
and y as a tensor of zeros with the same shape as x.
Return a boolean tensor that yields Trues if x equals y element-wise.
Hint: Look up tf.equal().

In [8]:
sess3 = tf.InteractiveSession()
x = tf.Variable([[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)
opt = tf.equal(
    x,
    y,
    name=None
)
init_op = tf.global_variables_initializer()
sess3.run(init_op)
print(x.eval())
print(y.eval())
print(opt.eval())
sess3.close()

[[ 0 -2 -1]
 [ 0  1  2]]
[[0 0 0]
 [0 0 0]]
[[ True False False]
 [ True False False]]


1d: Use the tensor x given below.
Get the indices of elements in x whose values are greater than 30.
Hint: Use tf.where().
Then extract elements whose values are greater than 30.
Hint: Use tf.gather().

In [13]:
sess4 = tf.InteractiveSession()
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
		        30.97266006,  26.67541885,  38.08450317,  20.74983215,
		        34.94445419,  34.45999146,  29.06485367,  36.01657104,
		        27.88236427,  20.56035233,  30.20379066,  29.51215172,
		        33.71149445,  28.59134293,  36.05556488,  28.66994858])
y = tf.where(x>30)
z = tf.gather(x,y)
print(y.eval())
print(z.eval())
sess4.close()

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
2, ..., 6
Hint: Use tf.range() and tf.diag().

In [15]:
ran = tf.range(1,7,1)
x = tf.diag(ran)
print(x.eval())

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
Calculate its determinant.
Hint: Look at tf.matrix_determinant().

In [24]:
x = tf.random_uniform((10,10))
z = tf.matrix_determinant(x)
print(x.eval())
print("\n determinant is {}".format(z.eval()))

[[0.7140032  0.51937246 0.51099634 0.5493525  0.84858966 0.5415126
  0.6414683  0.1673826  0.27645433 0.26956654]
 [0.00287139 0.3538648  0.98332524 0.7985915  0.34319556 0.58136404
  0.93569434 0.9654541  0.3672291  0.46427894]
 [0.6239389  0.13721514 0.4365548  0.09077096 0.86143076 0.20224571
  0.56747913 0.8036746  0.8689141  0.7708293 ]
 [0.26493287 0.9164628  0.80329883 0.7086811  0.03713536 0.42298555
  0.85527706 0.61061037 0.5320908  0.5323057 ]
 [0.16729653 0.00977409 0.3681177  0.17844748 0.18716216 0.94372654
  0.29333544 0.13748002 0.71874595 0.08269179]
 [0.7320868  0.27431476 0.0766834  0.47121167 0.06442261 0.3626554
  0.84890676 0.9923383  0.4007157  0.7163614 ]
 [0.1311711  0.19461036 0.46812034 0.3531803  0.05374575 0.5705708
  0.9749639  0.7052152  0.91423464 0.637349  ]
 [0.4528545  0.729264   0.34014118 0.55561876 0.11946416 0.6667528
  0.5095016  0.8162676  0.525149   0.17462158]
 [0.8468456  0.75359905 0.10612047 0.52815926 0.67720115 0.20487487
  0.5676074  0.1

1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
Return the unique elements in x
Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.

In [32]:
sess = tf.InteractiveSession()
x = tf.Variable([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
init = tf.global_variables_initializer()
sess.run(init)
z,_ = tf.unique(x)
print(x.eval())
print(z.eval())

[ 5  2  3  5 10  6  2  3  4  2  1  1  0  9]
[ 5  2  3 10  6  4  1  0  9]


1h: Create two tensors x and y of shape 300 from any normal distribution,
as long as they are from the same distribution.
Use tf.cond() to return:
- The mean squared error of (x - y) if the average of all elements in (x - y)
  is negative, or
- The sum of absolute value of all elements in the tensor (x - y) otherwise.
Hint: see the Huber loss function in the lecture slides 3.

In [44]:
sess = tf.InteractiveSession()
x = tf.random_uniform((300,1))
y = tf.random_uniform((300,1))
z = tf.subtract(x,y)
avg = tf.reduce_mean(z)
init = tf.global_variables_initializer()
sess.run(init)
out = tf.cond(avg.eval()>0,lambda:tf.nn.l2_loss(z),lambda:tf.reduce_mean(tf.abs(z)))
print(out.eval())

25.379845
